" preference file for vim

" show line numbers
set number

" Always  set auto indenting on
set autoindent

" select when using the mouse
set selectmode=mouse

" show the cursor position all the time
set ruler

" I like this as it makes reading texts easier (for me, at least).
set joinspaces

" Syntax highlighting on
syntax enable

colorscheme desert

" To insert text without auto-indenting
set pastetoggle=<F2>

" Set tab length
set tabstop=4

" Set R language recognisation:
au BufRead,BufNewFile *.R set filetype=R
au BufRead,BufNewFile *.r set filetype=R

au! Syntax newlang source ~/.vim/r.vim

set tabstop=4
set shiftwidth=4
set expandtab

" Set a better escape key (option-period)
imap ≥ <Esc>

" Case insensitive searching by default
set ignorecase

" Highlighting search
set hlsearch

" Allow mouse use
set mouse=a

" Custom syntax highlighting definitions
au BufNewFile,BufRead Snakefile set syntax=snakemake
au BufNewFile,BufRead *.smk set syntax=snakemake

" Nextflow groovy highlighting
" autocmd BufNewFile,BufRead *.nf set filetype=groovy

" Update fast for gitgutter
set updatetime=100

call plug#begin()
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
"Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
"Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
"Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
"Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
"Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-default branch
"Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
"Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
"Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
"Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
"Plug '~/my-prototype-plugin'

Plug 'Mxrcon/nextflow-vim'

" Initialize plugin system
" - Automatically executes `filetype plugin indent on` and `syntax enable`.
call plug#end()
" You can revert the settings after the call like so:
"   filetype indent off   " Disable file-type-specific indentation
"   syntax off            " Disable syntax highlighting
