# echo "Bash profile running" 1>&2

##
# Your previous /Users/tankard/.bash_profile file was backed up as /Users/tankard/.bash_profile.macports-saved_2012-04-20_at_13:57:15
##

# Run common profile
. ~/.shell_profile

# Run .bashrc things
. ~/.bashrc
 

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/tankard/Applications/google-cloud-sdk/path.bash.inc' ]; then . '/Users/tankard/Applications/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/tankard/Applications/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/tankard/Applications/google-cloud-sdk/completion.bash.inc'; fi
